-- PASO 7A.1 - Control Plane SaaS
-- Database-per-Tenant: this script creates metadata only; it never creates tenant databases.

CREATE SCHEMA IF NOT EXISTS saas_control;

CREATE TABLE IF NOT EXISTS saas_control.empresa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    slug VARCHAR(80) NOT NULL UNIQUE,
    razon_social VARCHAR(160) NOT NULL,
    nombre_comercial VARCHAR(160) NOT NULL,
    nit VARCHAR(30) UNIQUE,
    correo VARCHAR(150) NOT NULL,
    telefono VARCHAR(30),
    direccion VARCHAR(255),
    logo_url VARCHAR(500),
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT empresa_codigo_no_vacio CHECK (btrim(codigo) <> ''),
    CONSTRAINT empresa_slug_no_vacio CHECK (btrim(slug) <> ''),
    CONSTRAINT empresa_slug_seguro CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT empresa_estado_chk CHECK (estado IN ('ACTIVA', 'SUSPENDIDA', 'PENDIENTE'))
);

CREATE TABLE IF NOT EXISTS saas_control.plan_saas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    precio_mensual NUMERIC(12, 2) NOT NULL,
    moneda VARCHAR(3) NOT NULL DEFAULT 'BOB',
    limite_usuarios INTEGER NOT NULL,
    limite_almacenamiento_mb INTEGER NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT plan_precio_chk CHECK (precio_mensual >= 0),
    CONSTRAINT plan_limite_usuarios_chk CHECK (limite_usuarios > 0),
    CONSTRAINT plan_limite_almacenamiento_chk CHECK (limite_almacenamiento_mb > 0),
    CONSTRAINT plan_moneda_chk CHECK (moneda ~ '^[A-Z]{3}$')
);

CREATE TABLE IF NOT EXISTS saas_control.suscripcion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado VARCHAR(20) NOT NULL,
    renovacion_auto BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT suscripcion_empresa_fk FOREIGN KEY (empresa_id)
        REFERENCES saas_control.empresa (id) ON DELETE RESTRICT,
    CONSTRAINT suscripcion_plan_fk FOREIGN KEY (plan_id)
        REFERENCES saas_control.plan_saas (id) ON DELETE RESTRICT,
    CONSTRAINT suscripcion_fechas_chk CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT suscripcion_estado_chk CHECK (
        estado IN ('PENDIENTE', 'ACTIVA', 'SUSPENDIDA', 'VENCIDA', 'CANCELADA')
    ),
    CONSTRAINT suscripcion_natural_key UNIQUE (empresa_id, plan_id, fecha_inicio, fecha_fin)
);

CREATE TABLE IF NOT EXISTS saas_control.tenant_database (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL UNIQUE,
    database_name VARCHAR(63) NOT NULL UNIQUE,
    host_alias VARCHAR(100),
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    version_schema VARCHAR(30),
    fecha_provisionamiento TIMESTAMPTZ,
    ultima_verificacion TIMESTAMPTZ,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT tenant_database_empresa_fk FOREIGN KEY (empresa_id)
        REFERENCES saas_control.empresa (id) ON DELETE RESTRICT,
    CONSTRAINT tenant_database_name_chk CHECK (database_name ~ '^[a-z0-9_]{1,63}$'),
    CONSTRAINT tenant_database_estado_chk CHECK (
        estado IN ('PENDIENTE', 'PROVISIONANDO', 'ACTIVA', 'SUSPENDIDA', 'ERROR')
    )
);

CREATE TABLE IF NOT EXISTS saas_control.saas_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    rol VARCHAR(30) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    ultimo_acceso TIMESTAMPTZ,
    CONSTRAINT saas_usuario_rol_chk CHECK (rol IN ('SUPERADMIN', 'OPERADOR'))
);

CREATE TABLE IF NOT EXISTS saas_control.saas_bitacora (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saas_usuario_id BIGINT,
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT now(),
    ip INET,
    accion VARCHAR(100) NOT NULL,
    entidad_afectada VARCHAR(100),
    id_registro_afectado BIGINT,
    descripcion TEXT,
    resultado VARCHAR(20),
    CONSTRAINT saas_bitacora_usuario_fk FOREIGN KEY (saas_usuario_id)
        REFERENCES saas_control.saas_usuario (id) ON DELETE SET NULL,
    CONSTRAINT saas_bitacora_resultado_chk CHECK (resultado IS NULL OR resultado IN ('EXITO', 'ERROR'))
);

CREATE TABLE IF NOT EXISTS saas_control.provisionamiento_tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    tenant_database_id BIGINT NOT NULL UNIQUE,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    paso_actual VARCHAR(100),
    intentos INTEGER NOT NULL DEFAULT 0,
    fecha_inicio TIMESTAMPTZ,
    fecha_fin TIMESTAMPTZ,
    mensaje_error TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT provisionamiento_empresa_fk FOREIGN KEY (empresa_id)
        REFERENCES saas_control.empresa (id) ON DELETE RESTRICT,
    CONSTRAINT provisionamiento_database_fk FOREIGN KEY (tenant_database_id)
        REFERENCES saas_control.tenant_database (id) ON DELETE RESTRICT,
    CONSTRAINT provisionamiento_estado_chk CHECK (
        estado IN ('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'ERROR')
    ),
    CONSTRAINT provisionamiento_intentos_chk CHECK (intentos >= 0),
    CONSTRAINT provisionamiento_fechas_chk CHECK (fecha_fin IS NULL OR fecha_inicio IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE INDEX IF NOT EXISTS idx_empresa_estado ON saas_control.empresa (estado);
CREATE INDEX IF NOT EXISTS idx_suscripcion_empresa ON saas_control.suscripcion (empresa_id);
CREATE INDEX IF NOT EXISTS idx_suscripcion_estado_fecha_fin
    ON saas_control.suscripcion (estado, fecha_fin);
CREATE INDEX IF NOT EXISTS idx_tenant_database_estado ON saas_control.tenant_database (estado);
CREATE INDEX IF NOT EXISTS idx_bitacora_fecha_hora ON saas_control.saas_bitacora (fecha_hora);
CREATE INDEX IF NOT EXISTS idx_bitacora_usuario ON saas_control.saas_bitacora (saas_usuario_id);
CREATE INDEX IF NOT EXISTS idx_provisionamiento_empresa_estado
    ON saas_control.provisionamiento_tenant (empresa_id, estado);
CREATE INDEX IF NOT EXISTS idx_provisionamiento_estado ON saas_control.provisionamiento_tenant (estado);

-- Control Plane is backend-only. No direct frontend privileges are granted here.
REVOKE ALL ON SCHEMA saas_control FROM anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA saas_control FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA saas_control FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA saas_control
    REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA saas_control
    REVOKE ALL ON SEQUENCES FROM anon, authenticated;
