-- Apply on the control-plane database only, before enabling the backup API.
BEGIN;
CREATE TABLE IF NOT EXISTS saas_control.backup_tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES saas_control.empresa(id) ON DELETE RESTRICT,
    tenant_database_id BIGINT NOT NULL REFERENCES saas_control.tenant_database(id) ON DELETE RESTRICT,
    tipo VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    estado VARCHAR(20) NOT NULL DEFAULT 'EN_PROCESO',
    storage_key VARCHAR(255),
    nombre_archivo VARCHAR(160),
    formato VARCHAR(20),
    size_bytes BIGINT,
    sha256 VARCHAR(64),
    version_schema VARCHAR(30),
    fecha_inicio TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_fin TIMESTAMPTZ,
    creado_por_saas_usuario_id BIGINT REFERENCES saas_control.saas_usuario(id) ON DELETE SET NULL,
    mensaje_error TEXT,
    CONSTRAINT backup_tenant_tipo_chk CHECK (tipo IN ('MANUAL', 'AUTOMATICO', 'PRE_RESTORE')),
    CONSTRAINT backup_tenant_estado_chk CHECK (estado IN ('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'ERROR')),
    CONSTRAINT backup_tenant_size_chk CHECK (size_bytes IS NULL OR size_bytes > 0),
    CONSTRAINT backup_tenant_sha_chk CHECK (sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT backup_tenant_complete_chk CHECK (estado <> 'COMPLETADO' OR
        (storage_key IS NOT NULL AND nombre_archivo IS NOT NULL AND formato = 'CUSTOM'
         AND size_bytes > 0 AND sha256 IS NOT NULL AND fecha_fin IS NOT NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_backup_tenant_en_proceso
    ON saas_control.backup_tenant (tenant_database_id) WHERE estado = 'EN_PROCESO';
CREATE INDEX IF NOT EXISTS idx_backup_empresa_inicio
    ON saas_control.backup_tenant (empresa_id, fecha_inicio DESC);
CREATE INDEX IF NOT EXISTS idx_backup_estado_tipo
    ON saas_control.backup_tenant (estado, tipo);
REVOKE ALL ON saas_control.backup_tenant FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA saas_control FROM anon, authenticated;
COMMIT;
