-- PASO 8B - Automatic tenant backup policy (control-plane database only).
-- Additive migration. It never modifies database/saas_control/005_create_backup_tenant.sql.
BEGIN;

CREATE TABLE IF NOT EXISTS saas_control.backup_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL UNIQUE REFERENCES saas_control.empresa(id) ON DELETE RESTRICT,
    habilitado BOOLEAN NOT NULL DEFAULT TRUE,
    frecuencia VARCHAR(20) NOT NULL DEFAULT 'DIARIA',
    hora_local TIME NOT NULL,
    timezone VARCHAR(64) NOT NULL DEFAULT 'America/La_Paz',
    retencion_cantidad INTEGER NOT NULL DEFAULT 7,
    ultimo_backup_automatico TIMESTAMPTZ,
    proximo_backup TIMESTAMPTZ,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT backup_policy_frecuencia_chk CHECK (frecuencia IN ('DIARIA', 'SEMANAL', 'MENSUAL')),
    CONSTRAINT backup_policy_timezone_chk CHECK (btrim(timezone) <> ''),
    CONSTRAINT backup_policy_retencion_chk CHECK (retencion_cantidad BETWEEN 1 AND 365)
);

CREATE INDEX IF NOT EXISTS idx_backup_policy_habilitado
    ON saas_control.backup_policy (habilitado, proximo_backup);

-- Additive anchor for per-window automatic idempotency. NULL for MANUAL/PRE_RESTORE.
ALTER TABLE saas_control.backup_tenant
    ADD COLUMN IF NOT EXISTS ventana VARCHAR(80);

CREATE UNIQUE INDEX IF NOT EXISTS uq_backup_tenant_automatico_ventana
    ON saas_control.backup_tenant (empresa_id, ventana)
    WHERE tipo = 'AUTOMATICO' AND ventana IS NOT NULL AND estado <> 'ERROR';

REVOKE ALL ON saas_control.backup_policy FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA saas_control FROM anon, authenticated;

COMMIT;
