-- PASO 8C - Safe per-tenant restore metadata (control-plane database only).
-- Additive migration. It never modifies database/saas_control/001..006.
BEGIN;

-- Logical maintenance state used while a tenant is being restored.
-- This only WIDENS the allowed set for the exact same check constraint created
-- in 001; no existing validation rule is removed.
ALTER TABLE saas_control.tenant_database
    DROP CONSTRAINT IF EXISTS tenant_database_estado_chk;
ALTER TABLE saas_control.tenant_database
    ADD CONSTRAINT tenant_database_estado_chk CHECK (
        estado IN ('PENDIENTE', 'PROVISIONANDO', 'ACTIVA', 'SUSPENDIDA', 'ERROR', 'RESTAURANDO')
    );

CREATE TABLE IF NOT EXISTS saas_control.restore_tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES saas_control.empresa(id) ON DELETE RESTRICT,
    tenant_database_id BIGINT NOT NULL REFERENCES saas_control.tenant_database(id) ON DELETE RESTRICT,
    backup_id BIGINT NOT NULL REFERENCES saas_control.backup_tenant(id) ON DELETE RESTRICT,
    pre_restore_backup_id BIGINT REFERENCES saas_control.backup_tenant(id) ON DELETE RESTRICT,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    etapa VARCHAR(50),
    fecha_inicio TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_fin TIMESTAMPTZ,
    creado_por_saas_usuario_id BIGINT REFERENCES saas_control.saas_usuario(id) ON DELETE SET NULL,
    mensaje_error TEXT,
    rollback_estado VARCHAR(30),
    rollback_mensaje TEXT,
    CONSTRAINT restore_tenant_estado_chk CHECK (estado IN (
        'PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'ERROR',
        'ROLLBACK_EN_PROCESO', 'ROLLBACK_COMPLETADO', 'ROLLBACK_ERROR'
    )),
    CONSTRAINT restore_tenant_rollback_chk CHECK (
        rollback_estado IS NULL OR rollback_estado IN ('EN_PROCESO', 'COMPLETADO', 'ERROR')
    ),
    -- A successfully completed restore always owns its mandatory PRE_RESTORE.
    CONSTRAINT restore_tenant_complete_chk CHECK (
        estado <> 'COMPLETADO' OR (pre_restore_backup_id IS NOT NULL AND fecha_fin IS NOT NULL)
    )
);

-- At most one active restore per tenant: the reservation is PENDIENTE and the
-- destructive window is EN_PROCESO / ROLLBACK_EN_PROCESO. COMPLETADO/ERROR
-- release the tenant for a future restore.
CREATE UNIQUE INDEX IF NOT EXISTS uq_restore_tenant_activo
    ON saas_control.restore_tenant (tenant_database_id)
    WHERE estado IN ('PENDIENTE', 'EN_PROCESO', 'ROLLBACK_EN_PROCESO');

CREATE INDEX IF NOT EXISTS idx_restore_empresa_inicio
    ON saas_control.restore_tenant (empresa_id, fecha_inicio DESC);
CREATE INDEX IF NOT EXISTS idx_restore_estado
    ON saas_control.restore_tenant (estado);
CREATE INDEX IF NOT EXISTS idx_restore_backup
    ON saas_control.restore_tenant (backup_id);

REVOKE ALL ON saas_control.restore_tenant FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA saas_control FROM anon, authenticated;

COMMIT;
